using System;

namespace RabbitDB.Attributes
{
    [Serializable]
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class TableAttribute : Attribute
    {
        public string EntityName { get; set; }
        /// <summary>
        /// This primary keys override the 
        /// default table primary key(s).
        /// Seperate your primary keys by comma.
        /// </summary>
        public string AlternativePKs { get; set; }
        public bool AutoGenerated { get; set; }

        public bool ReadWithNolock { get; set; }

        public TableAttribute(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentNullException("name");

            this.EntityName = name;
            this.AutoGenerated = true;
            this.AlternativePKs = string.Empty;
        }
    }
}
