// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TableAttribute.cs" company="">
//   
// </copyright>
// <summary>
//   The table attribute.
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace RabbitDB.Attributes
{
    using System;

    /// <summary>
    /// The table attribute.
    /// </summary>
    [Serializable]
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class TableAttribute : Attribute
    {
        #region Constructors and Destructors

        /// <summary>
        /// Initializes a new instance of the <see cref="TableAttribute"/> class.
        /// </summary>
        /// <param name="name">
        /// The name.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// </exception>
        public TableAttribute(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new ArgumentNullException("name");
            }

            this.EntityName = name;
            this.AutoGenerated = true;
            this.AlternativePKs = string.Empty;
        }

        #endregion

        #region Public Properties

        /// <summary>
        /// This primary keys override the 
        /// default table primary key(s).
        /// Seperate your primary keys by comma.
        /// </summary>
        public string AlternativePKs { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether auto generated.
        /// </summary>
        public bool AutoGenerated { get; set; }

        /// <summary>
        /// Gets or sets the entity name.
        /// </summary>
        public string EntityName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether read with nolock.
        /// </summary>
        public bool ReadWithNolock { get; set; }

        #endregion
    }
}