using System;

namespace MicroORM.Base.Mapping
{
    [Serializable]
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
    public class TableAttribute : Attribute
    {
        public string EntityName { get; set; }
        public string PrimaryKey { get; set; }
        public bool AutoGenerated { get; set; }

        public TableAttribute(string name)
        {
            name.MustNotBeEmpty();
            this.EntityName = name;
            this.PrimaryKey = "Id";
            this.AutoGenerated = true;
        }
    }
}
