// --------------------------------------------------------------------------------------------------------------------
// <copyright file="TableAttribute.cs" company="">
//   
// </copyright>
// <summary>
//   The table attribute.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

#region using directives

using System;

#endregion

namespace RabbitDB.Contracts.Attributes
{
    /// <summary>
    ///     The table attribute.
    /// </summary>
    [Serializable]
    [AttributeUsage(AttributeTargets.Class)]
    public class TableAttribute : Attribute
    {
        #region Construction

        /// <summary>
        ///     Initializes a new instance of the <see cref="TableAttribute" /> class.
        /// </summary>
        /// <param name="name">
        ///     The name.
        /// </param>
        /// <exception cref="ArgumentNullException">
        /// </exception>
        public TableAttribute(string name)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new ArgumentNullException(nameof(name));
            }

            EntityName = name;
            AutoGenerated = true;
            AlternativePKs = string.Empty;
        }

        #endregion

        #region  Properties

        /// <summary>
        ///     This primary keys override the
        ///     default table primary key(s).
        ///     Seperate your primary keys by comma.
        /// </summary>
        public string AlternativePKs { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether auto generated.
        /// </summary>
        public bool AutoGenerated { get; set; }

        /// <summary>
        ///     Gets or sets the entity name.
        /// </summary>
        public string EntityName { get; set; }

        /// <summary>
        ///     Gets or sets a value indicating whether read with nolock.
        /// </summary>
        public bool ReadWithNolock { get; set; }

        #endregion
    }
}